### ISSUE TITLE
`baseURL` option is not working with `loader.http`

### ISSUE THREAD

**Issue by ydlamba** [vega/vega-loader#7]
`loader.load(url, {baseURL: 'example.xyz'})` is working as expected _i.e_ loading data from **example.xyz/url** but the `loader.http(url, {baseURL: 'example.xyz'})` is fetching data from **url** (without the base) I guess it should be also **example.xyz/url**.

**Comment by jheer** [comment]
Yes, this is by design. The `http` method performs an HTTP request with a _post-sanitization_ URL. It is the job of the `sanitize` method to ensure the URL is acceptable and to add baseURL, etc as needed.

If you wish to call `http` directly, I recommend first calling `sanitize` in a Promise chain. For example, see https://github.com/vega/vega-loader/blob/master/src/loader.js#L51

However, the intended use case is to call `load` directly!
